/*
 * Generated with the help of claude sonnet 4.5
 */

import { Plugin, ResolvedConfig } from 'vite';
import { writeFileSync, mkdirSync } from 'fs';
import { resolve, join, basename } from 'path';
import { glob } from 'glob';
import { parseExpression } from 'cron-parser';
import { build } from 'vite';

interface WorkflowPluginOptions {
  pattern?: string;
  outDir?: string;
  pathPlaceholder?: string;
}

interface WorkflowInfo {
  filePath: string;
  name: string;
  schedule: string;
}

export function workflow(options: WorkflowPluginOptions = {}): Plugin {
  const {
    pattern = '**/*.workflow.ts',
    outDir = 'dist/workflows',
    pathPlaceholder = '{{WORKFLOW_PATH}}'
  } = options;

  let config: ResolvedConfig;
  const workflows: WorkflowInfo[] = [];

  return {
    name: 'vite-plugin-workflow',

    configResolved(resolvedConfig) {
      config = resolvedConfig;
    },

    async buildStart() {
      // Discover workflow files
      const workflowFiles = await glob(pattern, {
        cwd: config.root,
        absolute: true
      });

      workflows.length = 0;

      for (const filePath of workflowFiles) {
        try {
          // Dynamically import to validate exports
          const module = await import(filePath);

          if (!module.schedule) {
            console.warn(`⚠️  Workflow ${filePath} missing 'schedule' export. Skipping.`);
            continue;
          }

          if (!module.default || typeof module.default !== 'function') {
            console.warn(`⚠️  Workflow ${filePath} missing default function export. Skipping.`);
            continue;
          }

          // Validate cron expression
          try {
            parseExpression(module.schedule);
          } catch (err) {
            console.warn(`⚠️  Workflow ${filePath} has invalid cron expression: "${module.schedule}". Skipping.`);
            continue;
          }

          const name = basename(filePath, '.workflow.ts');
          workflows.push({
            filePath,
            name,
            schedule: module.schedule
          });

          console.log(`✓ Discovered workflow: ${name} (${module.schedule})`);
        } catch (err) {
          console.warn(`⚠️  Failed to load workflow ${filePath}:`, err);
        }
      }
    },

    resolveId(id) {
      // Exclude workflow files from main bundle
      if (id.endsWith('.workflow.ts')) {
        return { id, external: true };
      }
    },

    async closeBundle() {
      if (workflows.length === 0) {
        console.log('No workflows found to build.');
        return;
      }

      const workflowOutDir = resolve(config.root, outDir);
      mkdirSync(workflowOutDir, { recursive: true });

      // Build each workflow as a separate bundle
      for (const workflow of workflows) {
        console.log(`Building workflow: ${workflow.name}...`);

        try {
          await build({
            root: config.root,
            configFile: false,
            build: {
              outDir: workflowOutDir,
              lib: {
                entry: workflow.filePath,
                formats: ['es'],
                fileName: () => `${workflow.name}.js`
              },
              rollupOptions: {
                external: [], // Include all dependencies
                output: {
                  banner: '#!/usr/bin/env node',
                  sourcemap: true
                }
              },
              emptyOutDir: false,
              minify: false
            },
            logLevel: 'warn'
          });

          console.log(`✓ Built workflow: ${workflow.name}.mjs`);
        } catch (err) {
          console.warn(`⚠️  Failed to build workflow ${workflow.name}:`, err);
        }
      }

      // Generate crontab file
      const crontabLines = [
        '# Auto-generated by vite-plugin-workflow',
        `# Deploy path: ${pathPlaceholder}`,
        ''
      ];

      for (const workflow of workflows) {
        const scriptPath = `${pathPlaceholder}/${workflow.name}.mjs`;
        const logPath = `${pathPlaceholder}/logs/${workflow.name}.log`;
        crontabLines.push(
          `${workflow.schedule} ${scriptPath} >> ${logPath} 2>&1`
        );
      }

      const crontabPath = join(workflowOutDir, 'crontab');
      writeFileSync(crontabPath, crontabLines.join('\n') + '\n');
      console.log(`✓ Generated crontab at ${crontabPath}`);
      console.log(`\nWorkflows built: ${workflows.length}`);
    }
  };
}

export default workflow;
